-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-05 09:29:49 ICT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE cthoadon (
    masp    VARCHAR2(20) NOT NULL,
    mahd    VARCHAR2(20) NOT NULL,
    sl      INTEGER,
    trigia  NUMBER(8)
);

ALTER TABLE cthoadon ADD CONSTRAINT cthoadon_pk PRIMARY KEY ( mahd,
                                                              masp );

CREATE TABLE ctphieukk (
    masp       VARCHAR2(20) NOT NULL,
    makk       VARCHAR2(20) NOT NULL,
    slhethong  INTEGER,
    slt        INTEGER,
    lydo       VARCHAR2(20)
);

ALTER TABLE ctphieukk ADD CONSTRAINT ctphieunhapv1_pk PRIMARY KEY ( masp,
                                                                    makk );

CREATE TABLE ctphieunhap (
    masp     VARCHAR2(20) NOT NULL,
    manh     VARCHAR2(20) NOT NULL,
    slnhap   INTEGER,
    gianhap  NUMBER(8)
);

ALTER TABLE ctphieunhap ADD CONSTRAINT ctphieunhap_pk PRIMARY KEY ( masp,
                                                                    manh );

CREATE TABLE ctphieuxuat (
    masp    VARCHAR2(20) NOT NULL,
    maxh    VARCHAR2(20) NOT NULL,
    slxuat  INTEGER
);

ALTER TABLE ctphieuxuat ADD CONSTRAINT ctphieuxuat_pk PRIMARY KEY ( masp,
                                                                    maxh );

CREATE TABLE hoadon (
    mahd    VARCHAR2(20) NOT NULL,
    ngayhd  DATE,
    makh    VARCHAR2(20) NOT NULL,
    manv    VARCHAR2(20) NOT NULL
);

ALTER TABLE hoadon ADD CONSTRAINT hoadon_pk PRIMARY KEY ( mahd );

CREATE TABLE khthanhvien (
    matv    VARCHAR2(20) NOT NULL,
    tentv   VARCHAR2(30),
    loaitv  VARCHAR2(20),
    diemtv  INTEGER
);

ALTER TABLE khthanhvien ADD CONSTRAINT khthanhvien_pk PRIMARY KEY ( matv );

CREATE TABLE loaisp (
    malsp   VARCHAR2(20) NOT NULL,
    tenlsp  VARCHAR2(20)
);

ALTER TABLE loaisp ADD CONSTRAINT loaisp_pk PRIMARY KEY ( malsp );

CREATE TABLE nhanvien (
    manv      VARCHAR2(20)
        CONSTRAINT nnc_nhanvien_manv NOT NULL,
    tennv     VARCHAR2(20),
    chucvu    VARCHAR2(23),
    ngayvl    DATE,
    ngaysinh  DATE,
    mucluong  NUMBER(8),
    username  VARCHAR2(20)
);

ALTER TABLE nhanvien ADD CONSTRAINT nhanvien_pk PRIMARY KEY ( manv );

CREATE TABLE phieukk (
    makk     VARCHAR2(20) NOT NULL,
    ngaytao  DATE
);

ALTER TABLE phieukk ADD CONSTRAINT phieuxhv1_pk PRIMARY KEY ( makk );

CREATE TABLE phieunh (
    manh    VARCHAR2(20) NOT NULL,
    ngaynh  DATE,
    nhacc   VARCHAR2(30)
);

ALTER TABLE phieunh ADD CONSTRAINT phieunh_pk PRIMARY KEY ( manh );

CREATE TABLE phieuxh (
    maxh    VARCHAR2(20) NOT NULL,
    ngayxh  DATE
);

ALTER TABLE phieuxh ADD CONSTRAINT phieuxh_pk PRIMARY KEY ( maxh );

CREATE TABLE sanpham (
    masp    VARCHAR2(20) NOT NULL,
    tensp   VARCHAR2(20),
    giaban  NUMBER(8),
    tgbh    NUMBER(2),
    hangsx  VARCHAR2(20),
    slton   INTEGER,
    mota    VARCHAR2(30),
    malsp   VARCHAR2(20) NOT NULL
);

ALTER TABLE sanpham ADD CONSTRAINT sanpham_pk PRIMARY KEY ( masp );

CREATE TABLE taikhoan (
    username  VARCHAR2(20) NOT NULL,
    password  VARCHAR2(20),
    loaitk    VARCHAR2(20)
);

ALTER TABLE taikhoan ADD CONSTRAINT taikhoan_pk PRIMARY KEY ( username );

ALTER TABLE cthoadon
    ADD CONSTRAINT cthoadon_hoadon_fk FOREIGN KEY ( mahd )
        REFERENCES hoadon ( mahd );

ALTER TABLE cthoadon
    ADD CONSTRAINT cthoadon_sanpham_fk FOREIGN KEY ( masp )
        REFERENCES sanpham ( masp );

ALTER TABLE ctphieukk
    ADD CONSTRAINT ctphieukk_phieukk_fk FOREIGN KEY ( makk )
        REFERENCES phieukk ( makk );

ALTER TABLE ctphieukk
    ADD CONSTRAINT ctphieukk_sanpham_fk FOREIGN KEY ( masp )
        REFERENCES sanpham ( masp );

ALTER TABLE ctphieunhap
    ADD CONSTRAINT ctphieunhap_phieunh_fk FOREIGN KEY ( manh )
        REFERENCES phieunh ( manh );

ALTER TABLE ctphieunhap
    ADD CONSTRAINT ctphieunhap_sanpham_fk FOREIGN KEY ( masp )
        REFERENCES sanpham ( masp );

ALTER TABLE ctphieuxuat
    ADD CONSTRAINT ctphieuxuat_phieuxh_fk FOREIGN KEY ( maxh )
        REFERENCES phieuxh ( maxh );

ALTER TABLE ctphieuxuat
    ADD CONSTRAINT ctphieuxuat_sanpham_fk FOREIGN KEY ( masp )
        REFERENCES sanpham ( masp );

ALTER TABLE hoadon
    ADD CONSTRAINT hoadon_khthanhvien_fk FOREIGN KEY ( makh )
        REFERENCES khthanhvien ( matv );

ALTER TABLE hoadon
    ADD CONSTRAINT hoadon_nhanvien_fk FOREIGN KEY ( manv )
        REFERENCES nhanvien ( manv );

ALTER TABLE nhanvien
    ADD CONSTRAINT nhanvien_taikhoan_fk FOREIGN KEY ( username )
        REFERENCES taikhoan ( username );

ALTER TABLE sanpham
    ADD CONSTRAINT sanpham_loaisp_fk FOREIGN KEY ( malsp )
        REFERENCES loaisp ( malsp );
        
drop sequence id_manv;
drop sequence id_mahd;
drop sequence id_malsp;
drop sequence id_matv;
drop sequence id_phieukk;
drop sequence id_phieunhap;
drop sequence id_phieuxuat;
drop sequence id_matv;
drop sequence id_masp;
-- MANV SEQUENCE
CREATE SEQUENCE id_manv
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    CYCLE
    CACHE 2;
-- MAHD SEQUENCE
CREATE SEQUENCE id_mahd
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    CYCLE
    CACHE 2;
-- MAPN SEQUENCE
CREATE SEQUENCE id_phieunhap
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    CYCLE
    CACHE 2;
-- MAPX SEQUENCE
CREATE SEQUENCE id_phieuxuat
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    CYCLE
    CACHE 2;
-- MAKK SEQUENCE
CREATE SEQUENCE id_phieukk
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    CYCLE
    CACHE 2;
-- MASP SEQUENCE
CREATE SEQUENCE id_masp
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    CYCLE
    CACHE 2;
-- MATV SEQUENCE
CREATE SEQUENCE id_matv
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    CYCLE
    CACHE 2;
-- MALSP SEQUENCE
CREATE SEQUENCE id_malsp
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000
    CYCLE
    CACHE 2;
    
INSERT INTO NHANVIEN (MANV, TENNV, CHUCVU, NGAYVL, NGAYSINH, MUCLUONG) VALUES(id_manv.NEXTVAL, 'Hùng', 'Qu?n lý',
            TO_DATE('2020-10-10','YYYY-MM-DD'), TO_DATE('2000-10-02','YYYY-MM-DD'), '1500000');
-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
