-- PROCEDURE NÂNG C?P THÀNH VIÊN T? STANDARD LÊN VIP N?U ?I?M TV > 100
SELECT DIEMTV, LOAITV FROM KHTHANHVIEN WHERE MATV = '6';
CREATE OR REPLACE PROCEDURE UPGRADE_LOAITV
AS 
    V_MATV      KHTHANHVIEN.MATV%TYPE;
    V_TENTV     KHTHANHVIEN.TENTV%TYPE;
    V_LOAITV    KHTHANHVIEN.LOAITV%TYPE;
    V_DIEMTV    KHTHANHVIEN.DIEMTV%TYPE;
    CURSOR cur IS SELECT MATV, TENTV, LOAITV, DIEMTV
                FROM KHTHANHVIEN;
BEGIN
    OPEN cur;
    LOOP
        FETCH cur INTO V_MATV, V_TENTV, V_LOAITV, V_DIEMTV;
        EXIT WHEN cur%FOUND = FALSE;
        IF V_DIEMTV > 100 THEN
            UPDATE KHTHANHVIEN
            SET LOAITV = 'Vip'
            WHERE V_MATV = MATV;
            DBMS_OUTPUT.PUT_LINE(V_MATV||' '||V_TENTV);
        END IF;
    END LOOP;
    CLOSE cur;
    commit;
END;
EXEC UPGRADE_LOAITV;

-- PROCEDURE SLEEP
CREATE OR REPLACE PROCEDURE sleep (in_time number)
AS
    v_now date;
    BEGIN
        SELECT SYSDATE
        INTO v_now
        FROM DUAL;
    LOOP
    EXIT WHEN v_now + (in_time * (1/86400)) <= SYSDATE;
    END LOOP;
end;


-- PROCEDURE L?Y RA T?NG S? TI?N MÀ KHTHANHVIEN ?Ã CHI VÀO CÁC HÓA ??N
CREATE OR REPLACE function TOTAL_COST_FOR_MEMBER (V_MATV KHTHANHVIEN.MATV%TYPE)
return CTHOADON.TRIGIA%TYPE
AS
    V_TOTAL_COST CTHOADON.TRIGIA%TYPE;
BEGIN
    SELECT  SUM(CTHD.TRIGIA) INTO V_TOTAL_COST
    FROM    (KHTHANHVIEN TV JOIN HOADON HD ON HD.MAKH = TV.MATV)
            JOIN CTHOADON CTHD ON CTHD.MAHD = HD.MAHD
    WHERE   TV.MATV = V_MATV;
    RETURN V_TOTAL_COST;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN NULL;       
END;

BEGIN
    dbms_output.PUT_LINE('T?ng s? ti?n thành viên này ?ã chi cho c?a hàng '||total_cost_for_member(99));
END;

-- Procedure in ra các hóa ??n mà nhân viên ?ã l?p
CREATE OR REPLACE PROCEDURE NHANVIEN_HOADON
IS
    V_MANV  NHANVIEN.MANV%TYPE;
    V_TENNV NHANVIEN.TENNV%TYPE;
    
    CURSOR C_1 IS SELECT MANV, TENNV
                FROM NHANVIEN;
BEGIN
    OPEN C_1;
    LOOP 
        FETCH C_1 INTO V_MANV, V_TENNV;
        EXIT WHEN C_1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_MANV||' '||V_TENNV);
        DECLARE
            CURSOR C_2 IS   SELECT HD.MAHD, SUM(CTHD.TRIGIA) as tong
            FROM            HOADON HD JOIN CTHOADON CTHD ON HD.MAHD = CTHD.MAHD
            WHERE           HD.MANV = V_MANV
            GROUP BY        HD.MAHD;
            
            V_MAHD          HOADON.MAHD%TYPE;
            TONG_TIEN       NUMBER;
        BEGIN
            OPEN C_2;
            LOOP
                FETCH C_2 INTO V_MAHD, TONG_TIEN;
                EXIT WHEN C_2%NOTFOUND;
                IF C_2%FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('Hóa ??n: '||V_MAHD||' có t?ng ti?n là: '||TONG_TIEN);
                END IF;
            END LOOP;
            CLOSE C_2;
        END;
    END LOOP;
    CLOSE C_1;
END;
EXEC NHANVIEN_HOADON();