-- Trigger set loai thanh vien
CREATE OR REPLACE TRIGGER SET_LOAITV
BEFORE UPDATE OR INSERT
ON KHTHANHVIEN
FOR EACH ROW
DECLARE 
    V_LOAITV KHTHANHVIEN.LOAITV%TYPE;
BEGIN
    IF :NEW.DIEMTV >= 100 THEN
        :NEW.LOAITV := 'Vip';
    ELSE 
        :NEW.LOAITV := 'Standard';
    END IF;
END;
-- TRIGGER UPDATE SANPHAM KHI THEM CTHD (cai nay cho lost update)
CREATE OR REPLACE TRIGGER UPDATE_QUANTITY_SP
BEFORE INSERT OR UPDATE ON CTHOADON
FOR EACH ROW
DECLARE
    v_slton SANPHAM.SLTON%TYPE;
BEGIN
    lock table sanpham in exclusive mode;
    SELECT SLTON INTO v_slton FROM SANPHAM WHERE MASP = 15;
    IF INSERTING THEN
        sleep(10);
        UPDATE sanpham
        SET SLTON = v_slton-:new.SL
        WHERE MASP = :NEW.MASP;
    END IF;
END;
COMMIT;