/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.CTHoaDonBLL;
import BLL.HoaDonBLL;
import DTO.SanPham;
import DTO.ThanhVien;
import BLL.SanPhamBLL;
import BLL.ThanhVienBLL;
import DTO.CTHoaDon;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class HoaDonThem extends javax.swing.JFrame {

  /**
   * Creates new form ThemSanPham
   */
  private boolean clicked = false;
  public int stt = 0;
  private int tongTien;

  public HoaDonThem() {
    initComponents();
    loadAllSanPham();
    loadAllThanhVien();
  }

  public void resetLayout() {
    DefaultTableModel CTHDmodel = (DefaultTableModel) tableCTHD.getModel();
    while (tableCTHD.getRowCount() > 0) {
      CTHDmodel.removeRow(0);
    }
    soluongTxt.setText("");
  }

  public void loadAllThanhVien() {
    DefaultTableModel Thanhvienmodel = (DefaultTableModel) tableThanhvien.getModel();
    ArrayList<ThanhVien> listThanhvien = BLL.ThanhVienBLL.getAllThanhVien();
    while (tableThanhvien.getRowCount() > 0) {
      Thanhvienmodel.removeRow(0);
    }
    for (ThanhVien thanhvien : listThanhvien) {
      Object[] row = {thanhvien.maTV, thanhvien.tenTV};
      Thanhvienmodel.addRow(row);
    }
  }

  public void loadAllSanPham() {
    DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();
    while (tableSanPham.getRowCount() > 0) {
      model.removeRow(0);
    }

    List<SanPham> listSanPham = SanPhamBLL.getAllSanPham();
    for (SanPham sp : listSanPham) {
      Object[] row = {sp.maSp, sp.tenSp, sp.slTon, sp.giaBan};
      model.addRow(row);
    }
    tableSanPham.setModel(model);
  }

  public int getRowbyId(String id) {
    for (int i = 0; i < tableCTHD.getRowCount(); i++) {
      if (Integer.parseInt(id) == Integer.parseInt(tableCTHD.getValueAt(i, 1).toString())) {
        return i;
      }
    }
    return -1;
  }

  public void tinhTongtien() {
    int tongtien = 0;
    Locale localeEN = new Locale("en", "EN");
    NumberFormat en = NumberFormat.getInstance(localeEN);
    for (int i = 0; i < tableCTHD.getRowCount(); i++) {
      tongtien += (int) tableCTHD.getValueAt(i, 3) * (int) tableCTHD.getValueAt(i, 4);
    }
    if (memberType.equals("Standard")) {
      tongtien = (int) (tongtien * 0.95);
    } else if (memberType.equals("Vip")) {
      tongtien = (int) (tongtien * 0.9);
    }
    this.tongTien = tongtien;
    tongtienTxt.setText(en.format(tongtien));
    return;
  }

  public void addRowCTHD(String masp, String tensp, int soluong, int giaban) {
    int tienHientai;
    int thanhtien = 0;
    if (getRowbyId(masp) == -1) {
      this.stt++;
      thanhtien = giaban * soluong;
      Object[] row = {this.stt, masp, tensp, soluong, giaban, thanhtien};
      DefaultTableModel model = (DefaultTableModel) tableCTHD.getModel();
      model.addRow(row);
    } else {
      int existRow = getRowbyId(masp);
      int slHientai = (int) tableCTHD.getValueAt(existRow, 3);
      tableCTHD.setValueAt(slHientai + soluong, existRow, 3);
    }
    tinhTongtien();

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    btnLuu = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    tableCTHD = new javax.swing.JTable();
    jLabel7 = new javax.swing.JLabel();
    BTThoat = new javax.swing.JButton();
    mathanhvienTxt = new javax.swing.JTextField();
    jScrollPane3 = new javax.swing.JScrollPane();
    tableThanhvien = new javax.swing.JTable();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    memberFilter = new javax.swing.JTextField();
    tongtienTxt = new javax.swing.JTextField();
    xoaCTHD = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    maspTxt = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    soluongTxt = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    tableSanPham = new javax.swing.JTable();
    jLabel4 = new javax.swing.JLabel();
    btnThemsanpham = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    Filter = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel2.setBackground(new java.awt.Color(0, 168, 232));

    jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel8.setText("Mã Thành Viên");

    btnLuu.setBackground(new java.awt.Color(0, 102, 204));
    btnLuu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-35.png"))); // NOI18N
    btnLuu.setText(" LƯU HD");
    btnLuu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLuuActionPerformed(evt);
      }
    });

    tableCTHD.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá Bán", "Thành Tiền"
      }
    ));
    tableCTHD.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    tableCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableCTHDMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tableCTHD);
    if (tableCTHD.getColumnModel().getColumnCount() > 0) {
      tableCTHD.getColumnModel().getColumn(0).setMaxWidth(70);
      tableCTHD.getColumnModel().getColumn(2).setPreferredWidth(120);
      tableCTHD.getColumnModel().getColumn(3).setMaxWidth(60);
      tableCTHD.getColumnModel().getColumn(5).setResizable(false);
    }

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("HÓA ĐƠN");

    BTThoat.setBackground(new java.awt.Color(255, 0, 51));
    BTThoat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    BTThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exit-35.png"))); // NOI18N
    BTThoat.setText(" THOÁT");
    BTThoat.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BTThoatActionPerformed(evt);
      }
    });

    mathanhvienTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
    mathanhvienTxt.setText("0");
    mathanhvienTxt.setEnabled(false);
    mathanhvienTxt.setFocusable(false);

    tableThanhvien.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
    tableThanhvien.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Mã Thành Viên", "Tên Thành Viên"
      }
    ));
    tableThanhvien.setRowMargin(0);
    tableThanhvien.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableThanhvienMouseClicked(evt);
      }
    });
    jScrollPane3.setViewportView(tableThanhvien);

    jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel9.setText("TÌM KIẾM THÀNH VIÊN");

    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-35.png"))); // NOI18N

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 8, Short.MAX_VALUE)
    );

    jLabel1.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
    jLabel1.setText("TỔNG TIỀN:");

    memberFilter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    memberFilter.setToolTipText("Tìm theo tên thành viên");
    memberFilter.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        memberFilterKeyReleased(evt);
      }
    });

    tongtienTxt.setEnabled(false);
    tongtienTxt.setFocusable(false);

    xoaCTHD.setBackground(new java.awt.Color(255, 0, 0));
    xoaCTHD.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    xoaCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-35.png"))); // NOI18N
    xoaCTHD.setText("  XÓA");
    xoaCTHD.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        xoaCTHDActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(BTThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(mathanhvienTxt))
            .addGap(0, 114, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10)
            .addGap(18, 18, 18)
            .addComponent(memberFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(xoaCTHD)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tongtienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(7, 7, 7)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(xoaCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tongtienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(15, 15, 15)
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(memberFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(11, 11, 11)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(mathanhvienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnLuu)
          .addComponent(BTThoat))
        .addGap(19, 19, 19))
    );

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 0, 660, 700));

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));

    maspTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
    maspTxt.setEnabled(false);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Số Lượng");

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("Mã Sản Phẩm");

    soluongTxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

    tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng Tồn", "Giá Bán"
      }
    ));
    tableSanPham.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableSanPhamMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tableSanPham);
    if (tableSanPham.getColumnModel().getColumnCount() > 0) {
      tableSanPham.getColumnModel().getColumn(0).setMaxWidth(50);
      tableSanPham.getColumnModel().getColumn(1).setPreferredWidth(150);
      tableSanPham.getColumnModel().getColumn(1).setMaxWidth(350);
      tableSanPham.getColumnModel().getColumn(2).setPreferredWidth(50);
      tableSanPham.getColumnModel().getColumn(2).setMaxWidth(50);
      tableSanPham.getColumnModel().getColumn(3).setPreferredWidth(100);
      tableSanPham.getColumnModel().getColumn(3).setMaxWidth(100);
    }

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("CHỌN SẢN PHẨM");

    btnThemsanpham.setBackground(new java.awt.Color(0, 168, 232));
    btnThemsanpham.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    btnThemsanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-35.png"))); // NOI18N
    btnThemsanpham.setText(" THÊM CTHD");
    btnThemsanpham.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnThemsanphamActionPerformed(evt);
      }
    });

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-35.png"))); // NOI18N

    Filter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    Filter.setToolTipText("");
    Filter.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        FilterKeyReleased(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(22, 22, 22)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(soluongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(maspTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnThemsanpham)))
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
              .addComponent(jLabel5)
              .addGap(18, 18, 18)
              .addComponent(Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(29, 29, 29))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(Filter))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(70, 70, 70)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(maspTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(soluongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(btnThemsanpham)
        .addContainerGap(138, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 700));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnThemsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemsanphamActionPerformed
      // TODO add your handling code here:
      try {
        int selected = tableSanPham.getSelectedRow();
        if (selected == -1) {
          JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn 1 sản phẩm", "Lỗi", JOptionPane.ERROR_MESSAGE);
          return;
        }
        String masp = tableSanPham.getValueAt(selected, 0).toString().trim();
        String tensp = tableSanPham.getValueAt(selected, 1).toString().trim();
        int giaban = Integer.parseInt(tableSanPham.getValueAt(selected, 3).toString());
        int soluong = Integer.parseInt(soluongTxt.getText().toString().trim());
        if ((int) tableSanPham.getValueAt(selected, 2) < soluong) {
          JOptionPane.showMessageDialog(rootPane, "Số lượng không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
          return;
        }
        addRowCTHD(masp, tensp, soluong, giaban);
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Thông tin không hộp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
      }

    }//GEN-LAST:event_btnThemsanphamActionPerformed

    private void BTThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTThoatActionPerformed
      // TODO add your handling code here:
      dispose();
    }//GEN-LAST:event_BTThoatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
      // TODO add your handling code here:
      try {
        if (tableCTHD.getRowCount() == 0) {
          JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn ít nhất 1 sản phẩm", "Chưa có sản phẩm", JOptionPane.ERROR_MESSAGE);
          return;
        }
        int maKh;
        if (mathanhvienTxt.getText().isEmpty()) {
          maKh = 0;
        } else {
          maKh = Integer.parseInt(mathanhvienTxt.getText());
        }
        int maNv = Login.maNv;
        List<CTHoaDon> cthoadon = new ArrayList<>();
        for (int i = 0; i < tableCTHD.getRowCount(); i++) {
          int maSp = Integer.parseInt(tableCTHD.getValueAt(i, 1).toString());
          int soluong = (int) tableCTHD.getValueAt(i, 3);
          cthoadon.add(new CTHoaDon(maSp, soluong));
        }
        HoaDonBLL.insertHoaDon(maKh, maNv, cthoadon);
        tongtienTxt.setText("0");
        QuanLyHoaDon.loadAllHoaDon();
        resetLayout();
        loadAllSanPham();
        JOptionPane.showMessageDialog(rootPane, "Tạo hóa đơn thành công");
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Thông tin không hộp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
      }

    }//GEN-LAST:event_btnLuuActionPerformed

  private void FilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FilterKeyReleased
    // TODO add your handling code here:       
    DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();
    String query = Filter.getText();
    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
    tableSanPham.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(query));
  }//GEN-LAST:event_FilterKeyReleased

  private void memberFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memberFilterKeyReleased
    // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) tableThanhvien.getModel();
    String query = memberFilter.getText();
    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
    tableThanhvien.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(query));
  }//GEN-LAST:event_memberFilterKeyReleased

  private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
    // TODO add your handling code here:
    int selected = tableSanPham.getSelectedRow();
    if (selected != -1) {
      maspTxt.setText(tableSanPham.getValueAt(selected, 0).toString());
    }
  }//GEN-LAST:event_tableSanPhamMouseClicked

  private void tableCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCTHDMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_tableCTHDMouseClicked

  private void tableThanhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThanhvienMouseClicked
    // TODO add your handling code here:
    int selected = tableThanhvien.getSelectedRow();
    String maTv = tableThanhvien.getValueAt(selected, 0).toString();
    if (selected != -1) {
      mathanhvienTxt.setText(maTv);
    }
    ThanhVien tv = ThanhVienBLL.getOneThanhVien(maTv);
    memberType = (tv.diemTV >= 5000) ? tv.loaiTV : "pre-member";
    tinhTongtien();
  }//GEN-LAST:event_tableThanhvienMouseClicked

  private void xoaCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaCTHDActionPerformed
    // TODO add your handling code here:
    // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) tableCTHD.getModel();
    int[] selected = tableCTHD.getSelectedRows();
    int del = 1;
    for (int i = 0; i < selected.length; i++) {
      model.removeRow(selected[i]);
      if (i < selected.length - 1) {
        selected[i + 1] = selected[i + 1] - del;
        del = del + 1;
      }
    }
    tinhTongtien();
    // Xuất hiện thông báo xóa thành công
    JOptionPane.showMessageDialog(rootPane, "Xóa chi tiết hóa đơn thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
  }//GEN-LAST:event_xoaCTHDActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(HoaDonThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(HoaDonThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(HoaDonThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(HoaDonThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new HoaDonThem().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BTThoat;
  private javax.swing.JTextField Filter;
  private javax.swing.JButton btnLuu;
  private javax.swing.JButton btnThemsanpham;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextField maspTxt;
  private javax.swing.JTextField mathanhvienTxt;
  private javax.swing.JTextField memberFilter;
  private javax.swing.JTextField soluongTxt;
  private javax.swing.JTable tableCTHD;
  private javax.swing.JTable tableSanPham;
  private javax.swing.JTable tableThanhvien;
  private javax.swing.JTextField tongtienTxt;
  private javax.swing.JButton xoaCTHD;
  // End of variables declaration//GEN-END:variables
  public String memberType = "";
}
